### ISSUE TITLE
Use the 0 from Mensch?

### ISSUE THREAD

**Issue by madrobby** [andreberg/Meslo-Font#1]
Hi Andre, 

Meslo is awesome! Do you think it would be possible to make a variation with the number 0 from the Mensch Menlo derivative font? The only thing that bugs me about Menlo is the zero, and Mensch has a nice one with a dot in the middle: http://robey.lag.net/2010/06/21/mensch-font.html

If you don't want to/don't have the time, would you share the adapted sources and explain what applications/tools you use for editing?

Thanks,
Best,
Thomas

**Comment by andreberg** [comment]
Thanks for the praise. I'll see what I can do. Could be a while though before I get to it. Feel free to remind me (just in case :)). As for tools I can recommend Fontographer 5. It's a new version and very enjoyable to use. If you have access to it, FontLab is the best.

**Comment by andreberg** [comment]
Added a dotted zero version to all styles. You can find the zip in the downloads section.
