### ISSUE TITLE
Uppercase G too large?

### ISSUE THREAD

**Issue by petersondrew** [andreberg/Meslo-Font#10]
I haven't compared on OSX, but on Windows 7 in several apps using the default font rendering API (SQL Server Management Studio, Sublimetext, etc) the capital G for Meslo LG S seems too tall compared to the other letters.
See the screenshot.
![Big G](http://i.minus.com/ibl4QVscAibYFG.PNG)

**Comment by macosxguru** [comment]
This is not repeated on  Mac OS X.

macosxguru

On Sep 5, 2012, at 5:42 PM, Drew Peterson notifications@github.com wrote:

> I haven't compared on OSX, but on Windows 7 in several apps using the default font rendering API (SQL Server Management Studio, Sublimetext, etc) the capital G for Meslo LG S seems too tall compared to the other letters.
> See the screenshot.
> 
> —
> Reply to this email directly or view it on GitHub.

Email: macosxguru@gmail.com
Web: http://scriptogr.am/ipadpedia and http://macosxguru.posterous.com
Twitter: http://twitter.com/macosxguru

**Comment by andreberg** [comment]
Should be fixed with v1.21.
