### ISSUE TITLE
Any chance for an XS?

### ISSUE THREAD

**Issue by cannikin** [andreberg/Meslo-Font#5]
Loving the different line gaps, but I was hoping for something about half-way between default Menlo and Meslo LG S. Textmate seems to add a little more leading to regular Menlo which is just about the amount I like. Meslo LG S is huge in comparison (Sublime Text w/ Meslo LG S on left and Textmate with Menlo on right): http://cl.ly/17400O3o0n2k083E131W

**Comment by andreberg** [comment]
Will have to experiment with some values when I am back home from my trip. 

By the way, there is a hidden user defaults setting for TextMate that lets you adjust the line spacing with a number value. It starts with Oak... then something. If I recall correctly it should be mentioned in TextMates help somewhere. You will find it most definately in the Secrets.app pref pane .. 

ah there it is. Its called OakLineHeightDelta. Secrets describes it as: "Sets the difference (in pixels) between a font’s built-in line height and the height used in TM."

**Comment by andreberg** [comment]
If you haven't switched to another font by now, the OS/2 metrics changes for Meslo LG S in the just released v1.20 should come close to what you were requesting.
