### ISSUE TITLE
Font is broken on Mountain Lion GM

### ISSUE THREAD

**Issue by MSch** [andreberg/Meslo-Font#8]
https://img.skitch.com/20120710-g6mqy6y5tef9ttcue88c19pw27.jpg

Any ideas why?

**Comment by Naatan** [comment]
Same problem here.

**Comment by metafour** [comment]
Thought I was just going crazy. Looks ok in Quicklook but I get the same issue with the DZ and non-DZ versions.

**Comment by jreljac** [comment]
Manually putting the font files in \Library\Fonts seemed to solve the problem for me.

**Comment by andreberg** [comment]
Sorry guys I am still on Snow Leopard ... Lion just didn't do it for me. I hear ML is quite good though so depending on support of the apps I need for my work I might upgrade soon-ish ;)

As for the problem at hand, either it gets confused with another font, or there's a hickup/mixup with the unicode page assignments. This would be my first guess. I do think its likely to be the first one though. It is curious that quicklook still displays it correctly. Until I upgrade I can only guess. Apologies for that.

**Comment by andreberg** [comment]
Also wanted to mention: anyone having a similar issue, please make sure you are not experiencing a corrupted font cache problem. 

I had this once where part of my font collection would show up as other font's code pages. 
A freeware tool called FontNuke fixed that for me at the time.

**Comment by josefvn** [comment]
I also had the issue with the font looking weird in Font Book, and Quick Look, but I copied it into \Library\Fonts as @jreljac mentioned. It will still look weird in Font Book, but when you actually use the font, in Eclipse for example, everything is working just perfect!
